-- v3.0.0-dev
-- NOT FOR PRODUCTION
-- EXPECT BUGS IN THIS VERSION

--[[
	Made by: veternitzz (@alex_black20101)
	
	A switch implementation in pure luau. Documentation and a usage example can be found on the github
	linked below:

	https://github.com/veternitzz/switch-luau/
	Licensed under the MIT License
]]

function Switch(variable: any, cases: {})
	local defaultRegistered = false
	local startingCase = 0
	local conditionMet = false

	defaultRegistered = true -- assume we have registered a default
end

return Switch